version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENV=production
      - GITHUB_APP_PEM_PATH=/run/secrets/github_app_pem
    restart: always
    secrets:
      - github_app_pem

  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    env_file:
      - .env
    volumes:
      - ./db_setup/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

secrets:
  github_app_pem:
    file: ./GITHUB_APP_NIGHTLY.pem